@startuml
left to right direction
title Use Case: System Configuration

actor "Quản trị viên (Admin)" as Admin
rectangle "Cấu hình Hệ thống" {
  usecase "Quản lý Nhóm thuốc (Category)" as UC_ManageCategory
  usecase "Quản lý Đơn vị tính (Unit)" as UC_ManageUnit
  usecase "Quản lý Nhà cung cấp" as UC_ManageSupplier
}

Admin --> UC_ManageCategory
Admin --> UC_ManageUnit
Admin --> UC_ManageSupplier
@enduml

